### ISSUE TITLE
When trying mostly http site it throws CouldNotDownloadCertificate 

### ISSUE THREAD

**Issue by Touseef993** [spatie/ssl-certificate#106]
when i try to search http site it is throwing error couldNotDownloadCertificate then reviewing the documentation i found that we can also pass url with the port now i m passing port 80 for http and get this  how can i get the information that the http site contains

![image](https://user-images.githubusercontent.com/45680294/61948671-f2e2a780-afc1-11e9-9cb7-1a1183d2842e.png)

**Comment by atymic** [comment]
You can't query a cert for a site that's not running HTTPS. It makes sense that an exception was thrown, perhaps it could be a bit more descriptive though, for example:

> Could not download certificate from http URL

**Comment by Touseef993** [comment]
@atymic 
yes exectly what i thought but i was confused because some site have ssl configured but somehow they are running on http instead of https so i wanted to be as clear as possible because i m working on site audit tool for a website. thankyou

**Comment by freekmurze** [comment]
This seems to be some kind of edge. I suspect mostly people will use this package on sites that don't run on port 80.

Feel free to submit a PR with tests if you feel this should be improved.
