### ISSUE TITLE
Detect server installation and not domain

### ISSUE THREAD

**Issue by AWateround** [spatie/ssl-certificate#107]
Tried to install with Composer (from domain) using last PHP version, while my server is set to PHP5 and throw an error:

"**[InvalidArgumentException]
  Package spatie/ssl-certificate at version  has a PHP requirement incompatible with your PHP version (5.6.40)**"

Tried to force, not working.

What about OpenSSL certificate from cPanel... ?

Thanks

**Comment by freekmurze** [comment]
Please upgrade to the latest version of PHP.
