### ISSUE TITLE
Set SSL option param "peer_name" with hostname value

### ISSUE THREAD

**Issue by genert** [spatie/ssl-certificate#112]
Due a unique domains setup of our websites, this package fails when trying to download the certificate.

The issue seems to lie in - https://www.php.net/manual/en/context.ssl.php#context.ssl.peer-name

> Peer name to be used. If this value is not set, then the name is guessed based on the hostname used when opening the stream.

When assigning the property for sslOptions list, it works.

**Comment by freekmurze** [comment]
We'll continue this in #113
