### ISSUE TITLE
Not Possible Create Certificate from hostname with none standard Ports

### ISSUE THREAD

**Issue by wolffc** [spatie/ssl-certificate#122]
currently there seems to be not "easy way" to create a certificate from a non standard port.

i would exprect to overwrite the default port with like this:
```php
$certificate = SslCertificate::createForHostName('spatie.be:1234');
```

**Comment by freekmurze** [comment]
Feel free to PR improvements (with tests) around this. 👍

**Comment by wolffc** [comment]
okay thanks will look into it. if i have some time.
