### ISSUE TITLE
Not working with invalid certificate

### ISSUE THREAD

**Issue by martin-ro** [spatie/ssl-certificate#124]
Maybe I missed how the package is supposed to work. I tried it with https://expired.badssl.com/ and a few others from badssl.com but I always get that the certificate could not be downloaded:

`
Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate\UnknownError: Could not download certificate for host expired.badssl.com because Could not connect to expired.badssl.com. in /home/vagrant/code/vendor/spatie/ssl-certificate/src/Exceptions/CouldNotDownloadCertificate.php:24
`

Only seems to work with valid certificates?

Best regards

**Comment by freekmurze** [comment]
Currently it indeed only works with valid ones. I welcome PRs that makes it work with invalid certificates.
