### ISSUE TITLE
Bug in method createFromFile

### ISSUE THREAD

**Issue by loigez** [spatie/ssl-certificate#125]
In  static method createFromFile (class SslCertificate) is used reference to the calling object:

> return $this->createFromString(file_get_contents($pathToCertificate));

Unfortunately it make an error

> Error thrown with message "Using $this when not in object context"
> 
> Stacktrace:
> #6 Error in vendor/spatie/ssl-certificate/src/SslCertificate.php:36
> #5 Spatie\SslCertificate\SslCertificate:createFromFile
> .....

**Comment by freekmurze** [comment]
Could you take a look and PR a fix @markvaneijk ?

**Comment by markvaneijk** [comment]
@freekmurze I will take a look and create a PR.

**Comment by markvaneijk** [comment]
@freekmurze Done in #127

**Comment by freekmurze** [comment]
Thanks!
