### ISSUE TITLE
Error in article

### ISSUE THREAD

**Issue by EmilMoe** [spatie/ssl-certificate#126]
Thanks for this package @freekmurze. Just a small note that you are missing a `$` in the article about this:

![image](https://user-images.githubusercontent.com/555083/77821464-bf28c600-70ea-11ea-955c-9bc69c41e2e3.png)

**Comment by EmilMoe** [comment]
Also `getExpirationDate ` is changed to `expirationDate()`

**Comment by EmilMoe** [comment]
Sorry for forgetting this link: https://freek.dev/530-validating-ssl-certificates-with-php

**Comment by freekmurze** [comment]
Fixed, thanks!
