### ISSUE TITLE
Internal Addresses Cannot Be Found

### ISSUE THREAD

**Issue by joeNTT** [spatie/ssl-certificate#128]
When I set the hostname to something such as google.com, this works great.  However, when I use it to test internal web servers I get errors that it cannot connect to the host?  I can reach those hosts via ping and via web browser from the server hosting the ssl-certificate code.  Thoughts?

Here is the error:
Fatal error: Uncaught Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate\UnknownError: Could not download certificate for host `agentsystems.clientinternal.net` because Could not connect to `agentsystems.clientinternal.net`. in C:\inetpub\wwwroot\HealthCheck\CertChecks\vendor\spatie\ssl-certificate\src\Exceptions\CouldNotDownloadCertificate.php:24 Stack trace: #0 C:\inetpub\wwwroot\HealthCheck\CertChecks\vendor\spatie\ssl-certificate\src\Downloader.php(171): Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate::unknownError('etcspn1uccefn1a...', 'Could not conne...') #1 C:\inetpub\wwwroot\HealthCheck\CertChecks\vendor\spatie\ssl-certificate\src\Downloader.php(90): Spatie\SslCertificate\Downloader->fetchCertificates('etcspn1uccefn1a...') #2 C:\inetpub\wwwroot\HealthCheck\CertChecks\vendor\spatie\ssl-certificate\src\Downloader.php(120): Spatie\SslCertificate\Downloader->getCertificates('etcspn1uccefn1a...') #3 C:\inetpub\wwwroot\HealthCheck\CertChecks\index.php(20): Spatie\SslCertificate\Downloader->forHost('e in C:\inetpub\wwwroot\HealthCheck\CertChecks\vendor\spatie\ssl-certificate\src\Exceptions\CouldNotDownloadCertificate.php on line 24

**Comment by freekmurze** [comment]
Seems like something specific to your server.

If you find the package is in error somehow, PR the fix 👍
