### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by victor-ponamariov** [spatie/ssl-certificate#129]
Hello and thanks for your awesome package!

I'm trying to store raw certificate data to the mysql database. For some domains I get `Malformed UTF-8 characters, possibly incorrectly encoded` when I try to insert into `json` column.

I see that I need to do some converting manipulations, but the array is multidimensional and it's not convenient to do it by hand. Probably there should be some workaround in the package itself? 

Just a suggestion

**Comment by freekmurze** [comment]
We're trying to keep the package as light as it can be, but feel free to send PRs.
