### ISSUE TITLE
Supporting resolution for hosts with non-standard ports

### ISSUE THREAD

**Issue by jmikola** [spatie/ssl-certificate#13]
I was hoping to use this library to help a user diagnose failed SSL certification verification for a database-as-a-service platform in https://github.com/mongodb/mongo-php-library/issues/313#issuecomment-267625578.

Unfortunately, the logic in [Downloader::downloadCertificateFromUrl()](https://github.com/spatie/ssl-certificate/blob/1.2.1/src/Downloader.php#L22) assumes a port of 443. This may be related to [Url::__construct()](https://github.com/spatie/ssl-certificate/blob/1.2.1/src/Url.php#L18) assuming an `http://` or `https://` scheme instead of allowing any scheme, as PHP's [`FILTER_VALIDATE_URL` does](https://github.com/php/php-src/blob/PHP-7.1.0/ext/filter/logical_filters.c#L517).

Are you open to allowing this functionality in a future version? If so, I'm willing to work on a PR if you have some feedback for how you'd like it implemented.

**Comment by freekmurze** [comment]
I've gone ahead and made some changes so a port can be easily specified a host starting with `ssl://` is accepted.

Using the code on the `master` branch could you try this against a real host on mongodb.net?

```
SslCertificate::download()
   ->usingPort(27017)
   ->forHost('ssl://example-shard-00-00-00000.mongodb.net');
```

If this works for you, I'll tag a new version.

**Comment by jmikola** [comment]
The code example was failing consistently with connection timeouts, until I realized that `Downloader::$timeout` was unassigned. I resolved this by adding a call to the fluent `setTimeout()` method before `forHost()`. Since `downloadCertificateFromUrl()` uses 30 seconds by default, I'd consider initializing the property to that as well.

The timeout issue also revealed an issue with `stream_socket_client()`'s error handling:

```
$ php test.php 
PHP Warning:  stream_socket_client(): unable to connect to ssl://cluster0-shard-00-00-4b82o.mongodb.net:27017 (Connection timed out) in /tmp/ssl-test/vendor/spatie/ssl-certificate/src/Downloader.php on line 56
PHP Warning:  stream_context_get_params() expects parameter 1 to be resource, boolean given in /tmp/ssl-test/vendor/spatie/ssl-certificate/src/Downloader.php on line 71
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Spatie\SslCertificate\SslCertificate::__construct() must be of the type array, boolean given, called in /tmp/ssl-test/vendor/spatie/ssl-certificate/src/Downloader.php on line 75 and defined in /tmp/ssl-test/vendor/spatie/ssl-certificate/src/SslCertificate.php:24
Stack trace:
#0 /tmp/ssl-test/vendor/spatie/ssl-certificate/src/Downloader.php(75): Spatie\SslCertificate\SslCertificate->__construct(false)
#1 /tmp/ssl-test/test.php(9): Spatie\SslCertificate\Downloader->forHost('cluster0-shard-...')
#2 {main}
  thrown in /tmp/ssl-test/vendor/spatie/ssl-certificate/src/SslCertificate.php on line 24
```

I see that you call the function in a `try` block and catch Throwables; however, it's still possible for the function to return `false` for some errors. I haven't played too much with Throwable errors in PHP 7, but my guess is that the warning for a timeout isn't severe enough to be converted into a Throwable. My PHP environment is 7.0.8 for reference.

Other than that, the library worked well when provided a usable timeout. Thanks!

**Comment by freekmurze** [comment]
Thanks for your feedback.

I tagged a new version `1.3.0` where all problems described above are fixed.
