### ISSUE TITLE
Is almost expired

### ISSUE THREAD

**Issue by DemianD** [spatie/ssl-certificate#2]
Hi,

I was looking for a method to determine of the SSL certificate is almost expired.

E.g.

```
$certificate->isAlmostExpired(7);
$certificate->isValid(7);
```

This methods will look if the certificate is valid, for at least 7 days.
isValid isn't possible because there is already a method with a parameter,
but isAlmostExpired isn't a good name (I think)

I can implement this method, and send a PR.
Demian

**Comment by jpmc** [comment]
Some suggestions perhaps are:
`$certificate->willExpire(7)`
`$certificate->willExpireWithin(7)`
`$certificate->willBeValid(7)`

or if you wish to continue keeping "is" as your function prefix:
`$certificate->isValidThrough(7)`
`$certificate->isValidFor(7)`
`$certificate->isExpiringIn(7)`

I'm sure there is a more succinct name out there somewhere, but hopefully these suggestions help.

**Comment by freekmurze** [comment]
I like to idea to add such a function.

Closing this issue, we'll discuss it further in #3
