### ISSUE TITLE
Dependency Injection for testing

### ISSUE THREAD

**Issue by laurencei** [spatie/ssl-certificate#20]
I'm having a bit of trouble using this package during an integration test. I want to mock out the `SslCertificate` during the tests.

But I cant seem to use DI for this class - because the `SslCertificate` wants a downloaded certificate during the constructor?

This is normally how I would use a package and allow for mocking:

`public function handle(SslCertificate $ssl)`

and use `$ssl` in my class. But that gives:

```
[Illuminate\Contracts\Container\BindingResolutionException] Unresolvable dependency resolving [Parameter #0 [ <required> array $downloadResults ]] in class \Spatie\SslCertificate\SslCertificate
```

And I cant resolve the class out of the IoC either:

`$ssl = app(\Spatie\SslCertificate\SslCertificate::class)`

Am I missing something? Is there a way to do this?

**Comment by freekmurze** [comment]
I'm thinking that in an vanilla Laravel application this should just work as [the constructor does nothing special](https://github.com/spatie/ssl-certificate/blob/master/src/SslCertificate.php#L24).

**Comment by sebastiandedeyne** [comment]
The `SslCertificate` class is an abstraction around the raw data concerning an existing SSL certificate, so yes it depends on an array of real data.

Why would you want to DI a class like this? It's not a service, it's more like some sort of value object (besides the static methods)

**Comment by laurencei** [comment]
I dont want to DI it specifically - I want/need to be able to mock it out.

i.e. I want to run a few tests on the higher level class that uses/calls `SslCertificate`. So I want to mock `SslCertificate` to run different things to simulate/mock the certificate, and allow the other class to be tested.

Is there a better way I should be doing this perhaps?

**Comment by freekmurze** [comment]
You could bind the value contextually:

```php
$this->app->when(\Spatie\SslCertificate\SslCertificate::class)
          ->needs('$rawCertificateFields')
          ->give($arrayWithRawCertificateFields);
```

**Comment by laurencei** [comment]
But how would I get `$arrayWithRawCertificateFields` in the live version?

i.e. in the test version I can have some premade array - so that is easy to bind contextually. But in the live versions I wouldnt be able to get that at the time of the container resolving the class?

Looking at the code - what if we add a `setRawCertificateFields()`? I could then construct with an empty array - and download the certificate after construction or mock out as needed?

Or is there a better option perhaps?

**Comment by freekmurze** [comment]
In the live version you would not do that binding. But that binding inside an `if` that checks if you are testing. 

In the live version the most common use case is that you just use the `download` method.

**Comment by laurencei** [comment]
Ok - what I've done is basically something like this:

```
if (App::environment('testing') {
    $ssl = app(\Spatie\SslCertificate\SslCertificate::class);
} else {
    $ssl = \Spatie\SslCertificate\SslCertificate::class;
}
```

So be able to inject (and therefore mock) during tests, otherwise hardcode it for live.

Seems to work.

Thanks @freekmurze and @sebastiandedeyne for your help.

**Comment by eleftrik** [comment]
> 

@laurencei I know this issue is almost 5 years old, but... I'm kinda stuck with the same problem.
Could you please explain how did you solve it?
Where did you put this if statement?

Thanks
