### ISSUE TITLE
Error, cannot find class

### ISSUE THREAD

**Issue by LetsGoPewPew** [spatie/ssl-certificate#21]
Hi. I have required the package as described via composer.
When i run this code: $certificate = SslCertificate::createForHostName('spatie.be');
i get the following error: 
Fatal error: Uncaught Error: Class 'SslCertificate' not found in C:\xampp\htdocs\Modules\httpsCheck.php:7
Do i need to do anything else than just composer require and include the autoload.php?
Thanks in advance.

**Comment by freekmurze** [comment]
You also need to import the right namespace.

Add this to the top of your script:

```php
use Spatie\SslCertificate\SslCertificate;
```

**Comment by LetsGoPewPew** [comment]
Wow, thank you so much for quick answer!
And i feel like i should have known that, sorry for the stupid question.
