### ISSUE TITLE
How can I check if website don't have SSL certificate ?

### ISSUE THREAD

**Issue by yorkbc2** [spatie/ssl-certificate#37]
I know, how to check website SSL certificate, but I don't know how to check if website don't have ssl ?

**Comment by freekmurze** [comment]
What's the output of `SslCertificate::createForHostName($websiteWithoutAnSslCertificate);`

**Comment by rxmg-nickk** [comment]
I had this exact same issue.

A function like this would be pretty useful.

    public function certificateExists($url)
    {
        try {
            SSLDownloader::downloadCertificateFromUrl($url);
        } catch (\CouldNotDownloadCertificate $e) {
            return false;
        }
        return true;
    }

**Comment by nkiermaier** [comment]
I had this exact same issue.

A function like this would be pretty useful.

    use Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate;

    public function certificateExists($url)
    {
        try {
            SSLDownloader::downloadCertificateFromUrl($url);
        } catch (\CouldNotDownloadCertificate $e) {
            return false;
        }
        return true;
    }

**Comment by freekmurze** [comment]
That function could to the trick.

**Comment by Touseef993** [comment]
> I had this exact same issue.
> 
> A function like this would be pretty useful.
> 
> ```
> use Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate;
> 
> public function certificateExists($url)
> {
>     try {
>         SSLDownloader::downloadCertificateFromUrl($url);
>     } catch (\CouldNotDownloadCertificate $e) {
>         return false;
>     }
>     return true;
> }
> ```

Can you please tell where to put this code i tried but failed
