### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by ato10** [spatie/ssl-certificate#53]
Hi, in README.md i read

> If the given hostName is invalid Spatie\SslCertificate\InvalidUrl will be thrown.
> ...
> Spatie\SslCertificate\CouldNotDownloadCertificate will be thrown.

I think it should be

> If the given hostName is invalid Spatie\SslCertificate\Exceptions\InvalidUrl will be thrown.
> ...
> Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate will be thrown.

**Comment by freekmurze** [comment]
Feel free to submit a PR to fix this 👍
