### ISSUE TITLE
Add a certificateExists method?

### ISSUE THREAD

**Issue by nkiermaier** [spatie/ssl-certificate#58]
Great package btw.
It throws errors on sites that don't have certificates.  
This would be a pretty cool option to have or something along these lines:

```
use Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate;

public function certificateExists($url)
{
    try {
        SSLDownloader::downloadCertificateFromUrl($url);
    } catch (\CouldNotDownloadCertificate $e) {
        return false;
    }
    return true;
}
```

**Comment by rxmg-nickk** [comment]
I could submit a P.R. if you guys would like.

**Comment by freekmurze** [comment]
Ok, be sure to include a test.

**Comment by HDVinnie** [comment]
any news on this?

**Comment by mutant-city** [comment]
I tried to make a simple method, however, theres nested certificates and cert chains that became more of a rabbit hole than I had hoped and had time for.

**Comment by HDVinnie** [comment]
will do thanks @mutant-city
