### ISSUE TITLE
Getting this error when trying to get my certificate. Not sure what's up.

### ISSUE THREAD

**Issue by nkiermaier** [spatie/ssl-certificate#59]
Spatie\SslCertificate\Exceptions\CouldNotDownloadCertificate with message 'Could not download certificate for host `site1.com` because PHP Warning:  stream_socket_client(): Peer certificate CN=`site2.com' did not match expected CN=`site1.com' in /Projects/trinity/vendor/spatie/ssl-certificate/src/Downloader.php on line 160'

**Comment by joshwillcock** [comment]
I seem to be getting similar errors:
Warning: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in vendor/spatie/ssl-certificate/src/Downloader.php on line 160
- Works with some domains but doesn't seem to work with all, not sure what it's issue is?

**Comment by mattiasgeniar** [comment]
Can you give the actual example of the domain you're using this against? We'll probably need a "live" version to troubleshoot.
