### ISSUE TITLE
`SslCertificate->isValid` does not work with uppercase subject alt names

### ISSUE THREAD

**Issue by mm-pagely** [spatie/ssl-certificate#66]
Given a cert with a subject alternative name field like:
```
DNS: WWW.FOO.COM, DNS: FOO.COM
```

`$cert->isValid('foo.com')` returns false because a case-sensitive comparison is done on all the subject alt names. Interestingly, the value passed into `isValid` is normalized to lower case, so even `$cert->isValid('FOO.COM')` returns false.

Per the RFC's:
* [IRI's in certificates](https://tools.ietf.org/html/rfc5280#section-7.4)
* [Case Normalization in IRI's](https://tools.ietf.org/html/rfc3987#section-5.3.2.1)

...both the scheme and hostname should be compared in a case-insensitive manner.

Seems as though the [`appliesToUrl` method](https://github.com/spatie/ssl-certificate/blob/master/src/SslCertificate.php#L158) should normalize all names to lowercase just before performing a comparison.

**Comment by mm-pagely** [comment]
Sorry for closing/re-opening--I fat-fingered things at first :)

**Comment by freekmurze** [comment]
We'll handle this further in #67
