### ISSUE TITLE
Call to undefined function Spatie\SslCertificate\idn_to_ascii()

### ISSUE THREAD

**Issue by Clement-Ruiz** [spatie/ssl-certificate#71]
Hello.
First of all, thank you for the work you're giving to provide these tools for free for community.

I've been trying to use your SslCertificate package for a single-page php file through composer (which I'm a bit novice with): 
``` php 
<?php
   error_reporting(E_ALL);
   ini_set('display_errors', 1);

   require __DIR__ . '/vendor/autoload.php';
   use Spatie\SslCertificate\SslCertificate;

   $certificate = SslCertificate::createForHostname('www.google.com');
   var_dump($certificate);
?>
```
My composer.json file is one of the simplest : 
``` json
{
    "require": {
        "spatie/ssl-certificate": "^1.12"
    }
}
```
I ran `composer install`, `composer update`, tried a `composer dump-autoload --optimize`, but I'm always obtaining the following traceback : 
``` html
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function Spatie\SslCertificate\idn_to_ascii() in /project/path/vendor/spatie/ssl-certificate/src/Url.php:21
Stack trace:
#0 /project/path/vendor/spatie/ssl-certificate/src/Downloader.php(123): Spatie\SslCertificate\Url-&gt;__construct('https://www.goo...')
#1 /project/path/vendor/spatie/ssl-certificate/src/Downloader.php(134): Spatie\SslCertificate\Downloader-&gt;forHost('www.google.com')
#2 /project/path/vendor/spatie/ssl-certificate/src/SslCertificate.php(25): Spatie\SslCertificate\Downloader::downloadCertificateFromUrl('www.google.com', 30)
#3 /project/path/test.php(8): Spatie\SslCertificate\SslCertificate::createForHostName('www.google.com')
#4 {main}
  thrown in <b>/project/path/vendor/spatie/ssl-certificate/src/Url.php</b> on line <b>21</b><br />
```
I'm using : 
* PHP 7.0.30-0ubuntu0.16.04.1 
* composer version 1.6.5

What am I getting wrong ?
Thanks for your time.

**Comment by Clement-Ruiz** [comment]
Alright,

Been a bit more through this, because `idn_to_ascii()` is an official PHP function ... but not in core php.
Seems like obvious for a lot of people, but it was actually difficult for me, as kind of neophyte, to find some precise documentation about this regarding the output.

In the end, Turns out that this package needs php7.0-intl installed on server to run successfully.

Maybe a "Requirements" section could be added to README.md.

Anyway thanks again for your work.
Regards

**Comment by krisnaw** [comment]
Hi, I have got the same exact error. How to solve it? Downgrade to Php 7?

**Comment by Clement-Ruiz** [comment]
Checkout http://php.net/manual/fr/book.intl.php
Regards

**Comment by mikkeschiren** [comment]
@krisnaw you need to install the php extensio intl

**Comment by ultrono** [comment]
Maybe unrelated, but I have the Intl extension installed. Passing a valid domain to `\Spatie\SslCertificate\Url` results in an `InvalidUrl` excpetion. 

On line 20 the `$url` variable is correct. On line 24 after the called to `idn_to_ascii()` `$url` is null.  

Everything works fine locally within LaraDock and Homestead. I'm assuming there's some additional requirement.

A horrible short term fix is simply commenting out line 22 at `\Spatie\SslCertificate\Url`, which of course is far from ideal.
