### ISSUE TITLE
Warning if certificate is expired

### ISSUE THREAD

**Issue by arnolem** [spatie/ssl-certificate#82]
Whis this code :
```php
$sslCertificate = SslCertificate::createForHostName($url);
\var_dump($sslCertificate->isValid());
```
I have a Warning
![image](https://user-images.githubusercontent.com/2263103/52676195-a2065780-2f29-11e9-94a1-4cc9eb4419f7.png)

But is just an expired certificate. 
![image](https://user-images.githubusercontent.com/2263103/52676223-bc403580-2f29-11e9-9086-af1201b2d2bf.png)

**Comment by freekmurze** [comment]
I don’t understand the issue. Could you give some more info?

**Comment by arnolem** [comment]
Your library displays warnings, but a third-party library should never display PHP warning.
Since you are using a PHP function that is not compatible with management by exception, I propose to make the warnings silentious -> https://github.com/arnolem/ssl-certificate/commit/88c93f8ecba271ce491d6055535be253e3247fa4
