### ISSUE TITLE
SSL chain resolution

### ISSUE THREAD

**Issue by mallardduck** [spatie/ssl-certificate#9]
For certain authorities having the full SSL chain is the best way to ensure that it's going to be fully valid and trusted by the connecting client.

As such, I believe there would be a huge benefit in modifying the Downloader class to get the full chain as well so that these could be tested and verified too. I know this would potentially require quite a bit of changes to how things are currently functioning, but I believe the efforts that this may take would be highly beneficial.

**Comment by freekmurze** [comment]
I'd accept a PR that verifies the entire chain.

**Comment by mallardduck** [comment]
Hello Gents,

So I've made quite a lot of progress in the area of parsing data from Self-Signed and Invalid SSLs. I've made major progress in the area of actually validating the SSL's status in multiple ways rather than simply parsing the data of valid SSLs. As my focus of interest was the actual validating aspect I (and my employer) have decided to fork the package due to the varying goals.

You can find that package here: [liquidweb/ssl-certificate](https://github.com/liquidweb/ssl-certificate)

In addition to the reasons mentioned, I also plan to add SMTP/IMAP protocol support for SSL testing; which will be a big departure from the this packages current scope. There are a few other similar requests I've gotten from internal sources as well.

At any rate, anyone interested should feel free to port over any of changes that will be accepted here.

Some highlights of current differences:

- Full SSL chain resolution: While they are not being validated against, when they exist I am grabbing SSL chains.
- Self-Signed & Invalid SSL support: You can now view information on Self-Signed and Invalid SSLs, making this a bit more useful when debugging issues.
- SSL CRL Checks: When an SSL is revoked you can use a few methods to check the status, OCSP or CRL. I've decided to add support for CRL based revocation checks.
- SSL Trust & Validity Status: With support for invalid and self-signed SSLs the package can now track/test for the Trust and Validity status of an SSL. Using these concepts you can determine more info on why an SSL may not be trusted by default.

Again, I'm completely in support of any/all of this being merged upstream.  If anyone is interested in working on that or would like my assistance on porting any changes up please feel free to shoot me a message.

Thanks,
Dan Pock
Liquid Web
